# Generated by Django 6.0.2 on 2026-02-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_transaction_due_date_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items borrowed in this transaction'),
        ),
    ]
