# Generated by Django 6.0.2 on 2026-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_transaction_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='Check if this is a group of identical items (like 5 brooms).'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1, help_text='Total number of items. Leave as 1 for unique items.'),
        ),
    ]
